name: flutter_mesh
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # mesh deps
  async: ^2.11.0
  flutter_blue_plus: ^1.31.16
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  uuid: ^4.3.3
  collection: ^1.18.0
  rxdart: ^0.27.7
  pointycastle: ^3.7.4 # TODO: maybe not needed in favor of `cryptography`
  cryptography: ^2.7.0
  cryptography_flutter: ^2.3.2

  # app deps
  flutter_hooks: ^0.20.5 # 0.21.0 has a bug!!!
  logger: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # mesh deps
  build_runner: ^2.4.8
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
